services:
  youtube-downloader:
    build: .
    container_name: youtube-downloader
    restart: unless-stopped
    ports:
      - "4655:8000"
    env_file:
      - .env
    volumes:
      - ./assets/downloads:/app/assets/downloads
      - ./config/config.yaml:/app/config/config.yaml
